!configdict
paths: !configdict
  beammap: ./darkness.bmap
  logs: ./logs/
  data: ./data/

packetmaster: !configdict
  ramdisk: /mnt/ramdisk # ramdisk directory to look for .img file made by packetmaster3's cuber routine
  nuller: False  # 1 if speckle nulling, 0 otherwise
  int_time: 1.0 # Cuber spits out images that are integrated over this amount of time
  ip: 10.0.0.51
  captureport: 50000

instrument : DARKNESS

detector: !configdict
  ncols: 80
  nrows: 125

roaches: !include roach.yml
