!configdict
paths: !configdict
  bin: /mnt/data0/ScienceData/Subaru/20191204/
  beammapdirectory: /mnt/data0/MEC/20191211/  # The location of the intermediate and final beammap files

beammap: !configdict

  filenames: !configdict
    initial_bmap:  # default mec.bmap in MKIDCore/mkidcore
    stage1_bmaps: '20191211_stage1_FL{}.txt'  # {date}_stage1_FL{x}.txt
    stage2_bmaps: '20191211_stage2_FL{}.txt'  # {date}_stage2_FL{x}.txt
    stage3_bmap: '20191211_stage3.txt'  # {date}_stage3.txt
    stage4_bmap: '20191211_stage4.txt'  # {date}_stage4.txt
    stage5_bmap: '20191211_stage5.bmap'  # {date}_stage5.bmap

  instrument: 'MEC'
  numCols: 140
  numRows: 146
  flip: False
  numfeedlines: 10

  ncpu: 12

  sweep: !configdict
    cachename: '_images_{}{}_phase={}.npz'  # (s.starttime, s.duration, get_phases)
    fittype: gaussian
    sweeps:
      - !configdict
        sweeptype: x
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575535711
        duration: 700

      - !configdict
        sweeptype: y
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575536445
        duration: 600

      - !configdict
        sweeptype: x
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575537067
        duration: 700

      - !configdict
        sweeptype: y
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575537812
        duration: 600

      - !configdict
        sweeptype: x
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575538434
        duration: 700

      - !configdict
        sweeptype: y
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575539173
        duration: 600

  align: !configdict
    cachename: '_imageFFT.npz'

  clean: !configdict
    usefreqs: False
    designMapFile: /home/data/MEC/20191204/mec_feedline.txt
    psFiles: /home/data/MEC/20191204/data/psData_*clipped.txt

