!configdict
paths: !configdict
  bin: /home/data/ScienceData/Subaru/20191204/  # todo convert to h5file directory
  beammapDirectory: /home/data/MEC/20191204/sweep/  # The location of the intermediate and final beammap files
  initialBeammap:   # flags all = 0. resID and row/col pixel nums all monotonically increase None to use the default for instrument
  temporalBeammap: beammap_20181218_FL1.bmap  # resID has associated times (not row col ints yet) (formerly roughbeammap)
  masterTemporalBeammap: beammap_20181219_all_clicked.bmap  # input for aligngrid. Concatenation of many feedlines manually clicked
  masterDoublesList:   #leave empty for case None
  alignedBeammap: RawMap20181218.txt  #aligned flagged beammap in pixel units (formerly raw map/output map)
  outputDoubleName:   #leave empty for case None
  designMapFile: /home/data/MEC/20191204/mec_feedline.txt
  quantizedBeammap: finalMapV1_1.txt  # quantized beammap

beammap: !configdict

  instrument: 'MEC'
  numCols: 140
  numRows: 146
  flip: False

  ncpu: 6

  sweep: !configdict
    fittype: gaussian
    sweeps:
      - !configdict
        sweeptype: x
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575527539
        duration: 700

      - !configdict
        sweeptype: y
        sweepdirection: +
        speed: 1
        size: 3
        starttime: 1575528461
        duration: 600

  align: placeholder

  clean: !configdict
    usefreqs: False
    psFiles: /home/data/MEC/20191204/data/psData_*clipped.txt
