# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beammap_gui.ui'
#
# Created: Thu Jan 17 17:24:56 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_beammap_gui(object):
    def setupUi(self, beammap_gui):
        beammap_gui.setObjectName(_fromUtf8("beammap_gui"))
        beammap_gui.resize(1520, 1100)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(beammap_gui.sizePolicy().hasHeightForWidth())
        beammap_gui.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(beammap_gui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.mapplot_0x = MPL_Widget(self.centralwidget)
        self.mapplot_0x.setGeometry(QtCore.QRect(10, 40, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_0x.setPalette(palette)
        self.mapplot_0x.setObjectName(_fromUtf8("mapplot_0x"))
        self.mapplot_0y = MPL_Widget(self.centralwidget)
        self.mapplot_0y.setGeometry(QtCore.QRect(10, 470, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_0y.setPalette(palette)
        self.mapplot_0y.setObjectName(_fromUtf8("mapplot_0y"))
        self.mapplot_1x = MPL_Widget(self.centralwidget)
        self.mapplot_1x.setGeometry(QtCore.QRect(310, 40, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_1x.setPalette(palette)
        self.mapplot_1x.setObjectName(_fromUtf8("mapplot_1x"))
        self.mapplot_1y = MPL_Widget(self.centralwidget)
        self.mapplot_1y.setGeometry(QtCore.QRect(310, 470, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_1y.setPalette(palette)
        self.mapplot_1y.setObjectName(_fromUtf8("mapplot_1y"))
        self.mapplot_2x = MPL_Widget(self.centralwidget)
        self.mapplot_2x.setGeometry(QtCore.QRect(610, 40, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_2x.setPalette(palette)
        self.mapplot_2x.setObjectName(_fromUtf8("mapplot_2x"))
        self.mapplot_2y = MPL_Widget(self.centralwidget)
        self.mapplot_2y.setGeometry(QtCore.QRect(610, 470, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_2y.setPalette(palette)
        self.mapplot_2y.setObjectName(_fromUtf8("mapplot_2y"))
        self.mapplot_3x = MPL_Widget(self.centralwidget)
        self.mapplot_3x.setGeometry(QtCore.QRect(910, 40, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_3x.setPalette(palette)
        self.mapplot_3x.setObjectName(_fromUtf8("mapplot_3x"))
        self.mapplot_3y = MPL_Widget(self.centralwidget)
        self.mapplot_3y.setGeometry(QtCore.QRect(910, 470, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_3y.setPalette(palette)
        self.mapplot_3y.setObjectName(_fromUtf8("mapplot_3y"))
        self.mapplot_4x = MPL_Widget(self.centralwidget)
        self.mapplot_4x.setGeometry(QtCore.QRect(1210, 40, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_4x.setPalette(palette)
        self.mapplot_4x.setObjectName(_fromUtf8("mapplot_4x"))
        self.mapplot_4y = MPL_Widget(self.centralwidget)
        self.mapplot_4y.setGeometry(QtCore.QRect(1210, 470, 301, 301))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.mapplot_4y.setPalette(palette)
        self.mapplot_4y.setObjectName(_fromUtf8("mapplot_4y"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(720, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.roachLabel = QtGui.QLabel(self.centralwidget)
        self.roachLabel.setGeometry(QtCore.QRect(740, 950, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.roachLabel.setFont(font)
        self.roachLabel.setObjectName(_fromUtf8("roachLabel"))
        self.nextbtn = QtGui.QPushButton(self.centralwidget)
        self.nextbtn.setGeometry(QtCore.QRect(340, 990, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextbtn.setFont(font)
        self.nextbtn.setObjectName(_fromUtf8("nextbtn"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 860, 1541, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.savebtn = QtGui.QPushButton(self.centralwidget)
        self.savebtn.setGeometry(QtCore.QRect(470, 990, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.savebtn.setFont(font)
        self.savebtn.setObjectName(_fromUtf8("savebtn"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 340, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 770, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pp0x = QtGui.QLabel(self.centralwidget)
        self.pp0x.setGeometry(QtCore.QRect(150, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp0x.setFont(font)
        self.pp0x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp0x.setObjectName(_fromUtf8("pp0x"))
        self.pp0y = QtGui.QLabel(self.centralwidget)
        self.pp0y.setGeometry(QtCore.QRect(150, 770, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp0y.setFont(font)
        self.pp0y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp0y.setObjectName(_fromUtf8("pp0y"))
        self.pp1x = QtGui.QLabel(self.centralwidget)
        self.pp1x.setGeometry(QtCore.QRect(450, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp1x.setFont(font)
        self.pp1x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp1x.setObjectName(_fromUtf8("pp1x"))
        self.pp1y = QtGui.QLabel(self.centralwidget)
        self.pp1y.setGeometry(QtCore.QRect(450, 770, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp1y.setFont(font)
        self.pp1y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp1y.setObjectName(_fromUtf8("pp1y"))
        self.pp2x = QtGui.QLabel(self.centralwidget)
        self.pp2x.setGeometry(QtCore.QRect(750, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp2x.setFont(font)
        self.pp2x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp2x.setObjectName(_fromUtf8("pp2x"))
        self.pp2y = QtGui.QLabel(self.centralwidget)
        self.pp2y.setGeometry(QtCore.QRect(750, 770, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp2y.setFont(font)
        self.pp2y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp2y.setObjectName(_fromUtf8("pp2y"))
        self.pp3x = QtGui.QLabel(self.centralwidget)
        self.pp3x.setGeometry(QtCore.QRect(1050, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp3x.setFont(font)
        self.pp3x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp3x.setObjectName(_fromUtf8("pp3x"))
        self.pp3y = QtGui.QLabel(self.centralwidget)
        self.pp3y.setGeometry(QtCore.QRect(1050, 770, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp3y.setFont(font)
        self.pp3y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp3y.setObjectName(_fromUtf8("pp3y"))
        self.pp4x = QtGui.QLabel(self.centralwidget)
        self.pp4x.setGeometry(QtCore.QRect(1350, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp4x.setFont(font)
        self.pp4x.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp4x.setObjectName(_fromUtf8("pp4x"))
        self.pp4y = QtGui.QLabel(self.centralwidget)
        self.pp4y.setGeometry(QtCore.QRect(1350, 770, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pp4y.setFont(font)
        self.pp4y.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pp4y.setObjectName(_fromUtf8("pp4y"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(300, -50, 20, 991))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(600, -60, 20, 1001))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(900, -80, 20, 1021))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(1200, -20, 20, 961))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 430, 1531, 20))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 370, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 800, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.le0x = QtGui.QLineEdit(self.centralwidget)
        self.le0x.setGeometry(QtCore.QRect(150, 370, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le0x.setFont(font)
        self.le0x.setObjectName(_fromUtf8("le0x"))
        self.le0y = QtGui.QLineEdit(self.centralwidget)
        self.le0y.setGeometry(QtCore.QRect(150, 800, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le0y.setFont(font)
        self.le0y.setObjectName(_fromUtf8("le0y"))
        self.le1x = QtGui.QLineEdit(self.centralwidget)
        self.le1x.setGeometry(QtCore.QRect(450, 370, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le1x.setFont(font)
        self.le1x.setObjectName(_fromUtf8("le1x"))
        self.le1y = QtGui.QLineEdit(self.centralwidget)
        self.le1y.setGeometry(QtCore.QRect(450, 800, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le1y.setFont(font)
        self.le1y.setObjectName(_fromUtf8("le1y"))
        self.le2x = QtGui.QLineEdit(self.centralwidget)
        self.le2x.setGeometry(QtCore.QRect(750, 370, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le2x.setFont(font)
        self.le2x.setObjectName(_fromUtf8("le2x"))
        self.le2y = QtGui.QLineEdit(self.centralwidget)
        self.le2y.setGeometry(QtCore.QRect(750, 800, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le2y.setFont(font)
        self.le2y.setObjectName(_fromUtf8("le2y"))
        self.le3x = QtGui.QLineEdit(self.centralwidget)
        self.le3x.setGeometry(QtCore.QRect(1050, 370, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le3x.setFont(font)
        self.le3x.setObjectName(_fromUtf8("le3x"))
        self.le3y = QtGui.QLineEdit(self.centralwidget)
        self.le3y.setGeometry(QtCore.QRect(1050, 800, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le3y.setFont(font)
        self.le3y.setObjectName(_fromUtf8("le3y"))
        self.le4x = QtGui.QLineEdit(self.centralwidget)
        self.le4x.setGeometry(QtCore.QRect(1350, 370, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le4x.setFont(font)
        self.le4x.setObjectName(_fromUtf8("le4x"))
        self.le4y = QtGui.QLineEdit(self.centralwidget)
        self.le4y.setGeometry(QtCore.QRect(1350, 800, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le4y.setFont(font)
        self.le4y.setObjectName(_fromUtf8("le4y"))
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(-10, 930, 1571, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.pix0 = QtGui.QLabel(self.centralwidget)
        self.pix0.setGeometry(QtCore.QRect(140, 910, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pix0.setFont(font)
        self.pix0.setObjectName(_fromUtf8("pix0"))
        self.pix1 = QtGui.QLabel(self.centralwidget)
        self.pix1.setGeometry(QtCore.QRect(440, 910, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pix1.setFont(font)
        self.pix1.setObjectName(_fromUtf8("pix1"))
        self.pix2 = QtGui.QLabel(self.centralwidget)
        self.pix2.setGeometry(QtCore.QRect(740, 910, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pix2.setFont(font)
        self.pix2.setObjectName(_fromUtf8("pix2"))
        self.pix3 = QtGui.QLabel(self.centralwidget)
        self.pix3.setGeometry(QtCore.QRect(1040, 910, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pix3.setFont(font)
        self.pix3.setObjectName(_fromUtf8("pix3"))
        self.pix4 = QtGui.QLabel(self.centralwidget)
        self.pix4.setGeometry(QtCore.QRect(1330, 910, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pix4.setFont(font)
        self.pix4.setObjectName(_fromUtf8("pix4"))
        self.a0 = QtGui.QRadioButton(self.centralwidget)
        self.a0.setGeometry(QtCore.QRect(70, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a0.setFont(font)
        self.a0.setChecked(True)
        self.a0.setAutoExclusive(False)
        self.a0.setObjectName(_fromUtf8("a0"))
        self.r0 = QtGui.QRadioButton(self.centralwidget)
        self.r0.setGeometry(QtCore.QRect(120, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r0.setFont(font)
        self.r0.setAutoExclusive(False)
        self.r0.setObjectName(_fromUtf8("r0"))
        self.x0 = QtGui.QRadioButton(self.centralwidget)
        self.x0.setGeometry(QtCore.QRect(170, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x0.setFont(font)
        self.x0.setAutoExclusive(False)
        self.x0.setObjectName(_fromUtf8("x0"))
        self.y0 = QtGui.QRadioButton(self.centralwidget)
        self.y0.setGeometry(QtCore.QRect(220, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y0.setFont(font)
        self.y0.setAutoExclusive(False)
        self.y0.setObjectName(_fromUtf8("y0"))
        self.x1 = QtGui.QRadioButton(self.centralwidget)
        self.x1.setGeometry(QtCore.QRect(470, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x1.setFont(font)
        self.x1.setAutoExclusive(False)
        self.x1.setObjectName(_fromUtf8("x1"))
        self.a1 = QtGui.QRadioButton(self.centralwidget)
        self.a1.setGeometry(QtCore.QRect(370, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a1.setFont(font)
        self.a1.setChecked(True)
        self.a1.setAutoExclusive(False)
        self.a1.setObjectName(_fromUtf8("a1"))
        self.y1 = QtGui.QRadioButton(self.centralwidget)
        self.y1.setGeometry(QtCore.QRect(520, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y1.setFont(font)
        self.y1.setAutoExclusive(False)
        self.y1.setObjectName(_fromUtf8("y1"))
        self.r1 = QtGui.QRadioButton(self.centralwidget)
        self.r1.setGeometry(QtCore.QRect(420, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r1.setFont(font)
        self.r1.setAutoExclusive(False)
        self.r1.setObjectName(_fromUtf8("r1"))
        self.x2 = QtGui.QRadioButton(self.centralwidget)
        self.x2.setGeometry(QtCore.QRect(770, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x2.setFont(font)
        self.x2.setAutoExclusive(False)
        self.x2.setObjectName(_fromUtf8("x2"))
        self.a2 = QtGui.QRadioButton(self.centralwidget)
        self.a2.setGeometry(QtCore.QRect(670, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a2.setFont(font)
        self.a2.setChecked(True)
        self.a2.setAutoExclusive(False)
        self.a2.setObjectName(_fromUtf8("a2"))
        self.y2 = QtGui.QRadioButton(self.centralwidget)
        self.y2.setGeometry(QtCore.QRect(820, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y2.setFont(font)
        self.y2.setAutoExclusive(False)
        self.y2.setObjectName(_fromUtf8("y2"))
        self.r2 = QtGui.QRadioButton(self.centralwidget)
        self.r2.setGeometry(QtCore.QRect(720, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r2.setFont(font)
        self.r2.setAutoExclusive(False)
        self.r2.setObjectName(_fromUtf8("r2"))
        self.x3 = QtGui.QRadioButton(self.centralwidget)
        self.x3.setGeometry(QtCore.QRect(1070, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x3.setFont(font)
        self.x3.setAutoExclusive(False)
        self.x3.setObjectName(_fromUtf8("x3"))
        self.a3 = QtGui.QRadioButton(self.centralwidget)
        self.a3.setGeometry(QtCore.QRect(970, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a3.setFont(font)
        self.a3.setChecked(True)
        self.a3.setAutoExclusive(False)
        self.a3.setObjectName(_fromUtf8("a3"))
        self.y3 = QtGui.QRadioButton(self.centralwidget)
        self.y3.setGeometry(QtCore.QRect(1120, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y3.setFont(font)
        self.y3.setAutoExclusive(False)
        self.y3.setObjectName(_fromUtf8("y3"))
        self.r3 = QtGui.QRadioButton(self.centralwidget)
        self.r3.setGeometry(QtCore.QRect(1020, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r3.setFont(font)
        self.r3.setAutoExclusive(False)
        self.r3.setObjectName(_fromUtf8("r3"))
        self.x4 = QtGui.QRadioButton(self.centralwidget)
        self.x4.setGeometry(QtCore.QRect(1370, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.x4.setFont(font)
        self.x4.setAutoExclusive(False)
        self.x4.setObjectName(_fromUtf8("x4"))
        self.a4 = QtGui.QRadioButton(self.centralwidget)
        self.a4.setGeometry(QtCore.QRect(1270, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.a4.setFont(font)
        self.a4.setChecked(True)
        self.a4.setAutoExclusive(False)
        self.a4.setObjectName(_fromUtf8("a4"))
        self.y4 = QtGui.QRadioButton(self.centralwidget)
        self.y4.setGeometry(QtCore.QRect(1420, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.y4.setFont(font)
        self.y4.setAutoExclusive(False)
        self.y4.setObjectName(_fromUtf8("y4"))
        self.r4 = QtGui.QRadioButton(self.centralwidget)
        self.r4.setGeometry(QtCore.QRect(1320, 880, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r4.setFont(font)
        self.r4.setAutoExclusive(False)
        self.r4.setObjectName(_fromUtf8("r4"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 400, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 830, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dle0x = QtGui.QLineEdit(self.centralwidget)
        self.dle0x.setGeometry(QtCore.QRect(150, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle0x.setFont(font)
        self.dle0x.setObjectName(_fromUtf8("dle0x"))
        self.dle0y = QtGui.QLineEdit(self.centralwidget)
        self.dle0y.setGeometry(QtCore.QRect(150, 830, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle0y.setFont(font)
        self.dle0y.setObjectName(_fromUtf8("dle0y"))
        self.dle1x = QtGui.QLineEdit(self.centralwidget)
        self.dle1x.setGeometry(QtCore.QRect(450, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle1x.setFont(font)
        self.dle1x.setObjectName(_fromUtf8("dle1x"))
        self.dle1y = QtGui.QLineEdit(self.centralwidget)
        self.dle1y.setGeometry(QtCore.QRect(450, 830, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle1y.setFont(font)
        self.dle1y.setObjectName(_fromUtf8("dle1y"))
        self.dle2x = QtGui.QLineEdit(self.centralwidget)
        self.dle2x.setGeometry(QtCore.QRect(750, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle2x.setFont(font)
        self.dle2x.setObjectName(_fromUtf8("dle2x"))
        self.dle2y = QtGui.QLineEdit(self.centralwidget)
        self.dle2y.setGeometry(QtCore.QRect(750, 830, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle2y.setFont(font)
        self.dle2y.setObjectName(_fromUtf8("dle2y"))
        self.dle3x = QtGui.QLineEdit(self.centralwidget)
        self.dle3x.setGeometry(QtCore.QRect(1050, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle3x.setFont(font)
        self.dle3x.setObjectName(_fromUtf8("dle3x"))
        self.dle3y = QtGui.QLineEdit(self.centralwidget)
        self.dle3y.setGeometry(QtCore.QRect(1050, 830, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle3y.setFont(font)
        self.dle3y.setObjectName(_fromUtf8("dle3y"))
        self.dle4x = QtGui.QLineEdit(self.centralwidget)
        self.dle4x.setGeometry(QtCore.QRect(1350, 400, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle4x.setFont(font)
        self.dle4x.setObjectName(_fromUtf8("dle4x"))
        self.dle4y = QtGui.QLineEdit(self.centralwidget)
        self.dle4y.setGeometry(QtCore.QRect(1350, 830, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dle4y.setFont(font)
        self.dle4y.setObjectName(_fromUtf8("dle4y"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 980, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 1020, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.roachgo = QtGui.QLineEdit(self.centralwidget)
        self.roachgo.setGeometry(QtCore.QRect(90, 980, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roachgo.setFont(font)
        self.roachgo.setObjectName(_fromUtf8("roachgo"))
        self.pixelgo = QtGui.QLineEdit(self.centralwidget)
        self.pixelgo.setGeometry(QtCore.QRect(90, 1020, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pixelgo.setFont(font)
        self.pixelgo.setObjectName(_fromUtf8("pixelgo"))
        self.gobtn = QtGui.QPushButton(self.centralwidget)
        self.gobtn.setGeometry(QtCore.QRect(150, 990, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gobtn.setFont(font)
        self.gobtn.setObjectName(_fromUtf8("gobtn"))
        self.ebtn0x = QtGui.QPushButton(self.centralwidget)
        self.ebtn0x.setGeometry(QtCore.QRect(230, 10, 75, 23))
        self.ebtn0x.setObjectName(_fromUtf8("ebtn0x"))
        self.ebtn0y = QtGui.QPushButton(self.centralwidget)
        self.ebtn0y.setGeometry(QtCore.QRect(230, 440, 75, 23))
        self.ebtn0y.setObjectName(_fromUtf8("ebtn0y"))
        self.ebtn1x = QtGui.QPushButton(self.centralwidget)
        self.ebtn1x.setGeometry(QtCore.QRect(530, 10, 75, 23))
        self.ebtn1x.setObjectName(_fromUtf8("ebtn1x"))
        self.ebtn1y = QtGui.QPushButton(self.centralwidget)
        self.ebtn1y.setGeometry(QtCore.QRect(530, 440, 75, 23))
        self.ebtn1y.setObjectName(_fromUtf8("ebtn1y"))
        self.ebtn2x = QtGui.QPushButton(self.centralwidget)
        self.ebtn2x.setGeometry(QtCore.QRect(830, 10, 75, 23))
        self.ebtn2x.setObjectName(_fromUtf8("ebtn2x"))
        self.ebtn2y = QtGui.QPushButton(self.centralwidget)
        self.ebtn2y.setGeometry(QtCore.QRect(830, 440, 75, 23))
        self.ebtn2y.setObjectName(_fromUtf8("ebtn2y"))
        self.ebtn3x = QtGui.QPushButton(self.centralwidget)
        self.ebtn3x.setGeometry(QtCore.QRect(1130, 10, 75, 23))
        self.ebtn3x.setObjectName(_fromUtf8("ebtn3x"))
        self.ebtn3y = QtGui.QPushButton(self.centralwidget)
        self.ebtn3y.setGeometry(QtCore.QRect(1130, 440, 75, 23))
        self.ebtn3y.setObjectName(_fromUtf8("ebtn3y"))
        self.ebtn4x = QtGui.QPushButton(self.centralwidget)
        self.ebtn4x.setGeometry(QtCore.QRect(1430, 10, 75, 23))
        self.ebtn4x.setObjectName(_fromUtf8("ebtn4x"))
        self.ebtn4y = QtGui.QPushButton(self.centralwidget)
        self.ebtn4y.setGeometry(QtCore.QRect(1430, 440, 75, 23))
        self.ebtn4y.setObjectName(_fromUtf8("ebtn4y"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(920, 970, 591, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        beammap_gui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(beammap_gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1520, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        beammap_gui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(beammap_gui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        beammap_gui.setStatusBar(self.statusbar)

        self.retranslateUi(beammap_gui)
        QtCore.QMetaObject.connectSlotsByName(beammap_gui)

    def retranslateUi(self, beammap_gui):
        beammap_gui.setWindowTitle(_translate("beammap_gui", "Beam Mapping", None))
        self.label.setText(_translate("beammap_gui", "X Sweeps", None))
        self.label_2.setText(_translate("beammap_gui", "Y Sweeps", None))
        self.roachLabel.setText(_translate("beammap_gui", "Roach 0", None))
        self.nextbtn.setText(_translate("beammap_gui", "Next", None))
        self.savebtn.setText(_translate("beammap_gui", "Save", None))
        self.label_3.setText(_translate("beammap_gui", "X Fit Position:", None))
        self.label_4.setText(_translate("beammap_gui", "Y Fit Position:", None))
        self.pp0x.setText(_translate("beammap_gui", "pp0x", None))
        self.pp0y.setText(_translate("beammap_gui", "pp0y", None))
        self.pp1x.setText(_translate("beammap_gui", "pp1x", None))
        self.pp1y.setText(_translate("beammap_gui", "pp1y", None))
        self.pp2x.setText(_translate("beammap_gui", "pp2x", None))
        self.pp2y.setText(_translate("beammap_gui", "pp2y", None))
        self.pp3x.setText(_translate("beammap_gui", "pp3x", None))
        self.pp3y.setText(_translate("beammap_gui", "pp3y", None))
        self.pp4x.setText(_translate("beammap_gui", "pp4x", None))
        self.pp4y.setText(_translate("beammap_gui", "pp4y", None))
        self.label_5.setText(_translate("beammap_gui", "X Self Position:", None))
        self.label_6.setText(_translate("beammap_gui", "Y Self Position:", None))
        self.le0x.setText(_translate("beammap_gui", "le0x", None))
        self.le0y.setText(_translate("beammap_gui", "le0y", None))
        self.le1x.setText(_translate("beammap_gui", "le1x", None))
        self.le1y.setText(_translate("beammap_gui", "le1y", None))
        self.le2x.setText(_translate("beammap_gui", "le2x", None))
        self.le2y.setText(_translate("beammap_gui", "le2y", None))
        self.le3x.setText(_translate("beammap_gui", "le3x", None))
        self.le3y.setText(_translate("beammap_gui", "le3y", None))
        self.le4x.setText(_translate("beammap_gui", "le4x", None))
        self.le4y.setText(_translate("beammap_gui", "le4y", None))
        self.pix0.setText(_translate("beammap_gui", "Pixel 0", None))
        self.pix1.setText(_translate("beammap_gui", "Pixel 1", None))
        self.pix2.setText(_translate("beammap_gui", "Pixel 2", None))
        self.pix3.setText(_translate("beammap_gui", "Pixel 3", None))
        self.pix4.setText(_translate("beammap_gui", "Pixel 4", None))
        self.a0.setText(_translate("beammap_gui", "A", None))
        self.r0.setText(_translate("beammap_gui", "R", None))
        self.x0.setText(_translate("beammap_gui", "X", None))
        self.y0.setText(_translate("beammap_gui", "Y", None))
        self.x1.setText(_translate("beammap_gui", "X", None))
        self.a1.setText(_translate("beammap_gui", "A", None))
        self.y1.setText(_translate("beammap_gui", "Y", None))
        self.r1.setText(_translate("beammap_gui", "R", None))
        self.x2.setText(_translate("beammap_gui", "X", None))
        self.a2.setText(_translate("beammap_gui", "A", None))
        self.y2.setText(_translate("beammap_gui", "Y", None))
        self.r2.setText(_translate("beammap_gui", "R", None))
        self.x3.setText(_translate("beammap_gui", "X", None))
        self.a3.setText(_translate("beammap_gui", "A", None))
        self.y3.setText(_translate("beammap_gui", "Y", None))
        self.r3.setText(_translate("beammap_gui", "R", None))
        self.x4.setText(_translate("beammap_gui", "X", None))
        self.a4.setText(_translate("beammap_gui", "A", None))
        self.y4.setText(_translate("beammap_gui", "Y", None))
        self.r4.setText(_translate("beammap_gui", "R", None))
        self.label_7.setText(_translate("beammap_gui", "X Double Position:", None))
        self.label_8.setText(_translate("beammap_gui", "Y Double Position:", None))
        self.dle0x.setText(_translate("beammap_gui", "dle0x", None))
        self.dle0y.setText(_translate("beammap_gui", "dle0y", None))
        self.dle1x.setText(_translate("beammap_gui", "dle1x", None))
        self.dle1y.setText(_translate("beammap_gui", "dle1y", None))
        self.dle2x.setText(_translate("beammap_gui", "dle2x", None))
        self.dle2y.setText(_translate("beammap_gui", "dle2y", None))
        self.dle3x.setText(_translate("beammap_gui", "dle3x", None))
        self.dle3y.setText(_translate("beammap_gui", "dle3y", None))
        self.dle4x.setText(_translate("beammap_gui", "dle4x", None))
        self.dle4y.setText(_translate("beammap_gui", "dle4y", None))
        self.label_9.setText(_translate("beammap_gui", "Roach", None))
        self.label_10.setText(_translate("beammap_gui", "Pixel", None))
        self.gobtn.setText(_translate("beammap_gui", "Go To", None))
        self.ebtn0x.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn0y.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn1x.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn1y.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn2x.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn2y.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn3x.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn3y.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn4x.setText(_translate("beammap_gui", "Enlarge", None))
        self.ebtn4y.setText(_translate("beammap_gui", "Enlarge", None))
        self.label_11.setText(_translate("beammap_gui", "Notes\n"
"1) Hit return to set self and double positions\n"
"2) Enlarged plots must be closed before setting self or double positions.", None))

from mpl_pyqt4_widget import MPL_Widget
